spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox0629e36e85c647868a768fc500c09248.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  #here is for production email sender with real url
  #email:
    #url: ""
  rate-limit:
    ip:
      apply-limit: true